development:
  adapter: postgresql
  database: text_scheduler_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: text_scheduler_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: text_scheduler
  pool: 5
  timeout: 5000

